version: "3"

vars:
  TFPLAN: .tfplan

# With AWS Credentials
dotenv: [ '.env' ]

tasks:
  tests:
    preconditions:
      - test -f .env
      - test -n $AWS_SECRET_ACCESS_KEY
      - test -n $AWS_ACCESS_KEY_ID
  
  infrastructure:init:
    deps: [ tests ]
    dir: 00_infrastructure/aws-bigdata-demo
    desc: Init terraform
    cmds:
      - terraform init

  infrastructure:plan:
    deps: [ infrastructure:init, tests ]
    dir: 00_infrastructure/aws-bigdata-demo
    desc: Show terraform resources creation
    cmds:
      - terraform plan -out={{.TFPLAN}}

  infrastructure:apply:
    deps: [ infrastructure:plan, tests ]
    dir: 00_infrastructure/aws-bigdata-demo
    desc: Apply resources creation
    cmds:
      - terraform apply "{{.TFPLAN}}"
  
  infrastructure:destroy:
    deps: [ tests ]
    dir: 00_infrastructure/aws-bigdata-demo
    desc: Apply resources creation
    cmds:
      - "terraform destroy -auto-approve"
  
  application:cdc-app-as-submodule-update:
    desc: Downloads the repository
    cmds:
      #- git submodule add "https://github.com/ZahidGalea/cdc-with-debezium-in-minikube" 01_sources/application-demo
      - git submodule update
  
  application:generate-app:
    deps: [ tests, application:cdc-app-as-submodule-update ]
    desc: Creates the application in minikube
    dir: 01_sources
    cmds:
      - /bin/bash init_application_demo.sh
  
  application:kafka-to-kinesis:
    deps: [ tests ]
    desc: Creates the application in minikube
    dir: 01_sources/kafka-to-kinesis
    cmds:
      - eval $(minikube docker-env); docker build -t=kafka-to-kinesis-app:latest .
      - kubectl delete secret aws-access | echo "not found"
      - kubectl create secret generic aws-access --from-literal=aws-secret-access-key=$AWS_SECRET_ACCESS_KEY --from-literal=aws-access-key-id=$AWS_ACCESS_KEY_ID
      - kubectl apply -f kafka-to-kinesis.yml
  
